In [1]:
import sqlite3 as sql
import pandas as pd

In [2]:
conn = sql.connect("tempdb.db")

try:
    conn.execute ("""
    drop table if exists manuf
    """)
    
    
    conn.execute ("""
    drop table if exists trademark
    """)
    
    conn.execute ("""
    drop table if exists type
    """)
    
    conn.execute ("""
    CREATE TABLE Manuf (ID INT, NAME TEXT, PRIMARY KEY ('id'));
    """)
    
    conn.execute ("""
                    
    CREATE TABLE type ( TYPENAME TEXT, Tradeowner INT,
                   foreign key ('tradeowner')
                    references trademark ('tradeID')
                    on delete cascade
                    on update cascade)
                    ;
      """)
    
    conn.execute ("""
                    
   CREATE TABLE trademark (vaccine TEXT, TradeID INT, 
                        OWNER INT, 
                    foreign key ('owner')
                    references Manuf ('id')
                    on delete cascade
                    on update cascade)
                    ;
      """)

    
    conn.executemany ("""
    Insert into manuf values (?,?)""",[ (1, 'Merk'),(2, 'Vtech'),(3, 'MSD'),(4, 'Biopharm'),(5, 'Zoetis')])
    
    conn.executemany ("""
    Insert into trademark values (?,?,?)""",[ ('coccivac D',1,1),
('coccivac B',2,1),
('Immucox C1',3,2),
('Immucox C2',4,2),
('Paracox-8',5,3),
('Paracox-5',6,3),
('Livacox D',7,4),
('Livacox T',8,4),
('Inovocox',9,5)])
    
    conn.executemany ("""
    Insert into type values (?,?)""",[ ('LIVE virulent', 1),
('LIVE virulent',2),
('LIVE virulent',3),
('LIVE virulent', 4),
('LIVE attenuated', 5),
('LIVE attenuated', 6),
('LIVE attenuated', 7),
('LIVE attenuated', 8),('LIVE attenuated', 9)])
    

    
    
    

    cursor = conn.execute("select * from trademark")
    
    df = pd.DataFrame(cursor.fetchall(),columns = ['vaccine','trademarkID','ManufacturorID'])
    print(df)
    
    cursor = conn.execute("select * from manuf")
    
    df = pd.DataFrame(cursor.fetchall(),columns = ['ManufacturorID','NAME'])
    print(df)
    
    cursor = conn.execute("select * from type")
    
    df = pd.DataFrame(cursor.fetchall(),columns = ['type','trademarkID'])
    print(df)
    
      
    cursor = conn.execute ("""select trademark.vaccine,trademark.tradeid,trademark.owner, type.typename,type.tradeowner
    from trademark join type
    on type.tradeowner=trademark.tradeid""")      
    
    print(cursor)

    conn.commit()


    

    
except sqlite3.error as e: 
    print ("there was error:" + str(e))    

        
finally:
    print ("this executed")
    conn.close()

      vaccine  trademarkID  ManufacturorID
0  coccivac D            1               1
1  coccivac B            2               1
2  Immucox C1            3               2
3  Immucox C2            4               2
4   Paracox-8            5               3
5   Paracox-5            6               3
6   Livacox D            7               4
7   Livacox T            8               4
8    Inovocox            9               5
   ManufacturorID      NAME
0               1      Merk
1               2     Vtech
2               3       MSD
3               4  Biopharm
4               5    Zoetis
              type  trademarkID
0    LIVE virulent            1
1    LIVE virulent            2
2    LIVE virulent            3
3    LIVE virulent            4
4  LIVE attenuated            5
5  LIVE attenuated            6
6  LIVE attenuated            7
7  LIVE attenuated            8
8  LIVE attenuated            9
<sqlite3.Cursor object at 0x1194a3490>
this executed